### ISSUE TITLE
Records wont get inserted in postgresql

### ISSUE THREAD

**Issue by HEMA-MATHAVAN** [nicbet/MailboxMiner#1]
hi,
i have followed the steps stated under 'usage' to reconstruct the database from dump.
Then i executed the import.sh file with the required arguments.
here is what i have done

[root@localhost dist]#  sh import.sh /home/hema/test_data //localhost:5432 testdb hema password

i am getting the following comments displayed.

Unpacking mbox files to /home/hema/MailboxMiner-master/MailboxMiner2/dist/tmp
Creating database testdb
[LOG] Connection to PostgreSQL 9.4.6 successful!
Dropping existing database testdb
Error dropping database testdb : ERROR: database "testdb" is being accessed by other users
  Detail: There is 1 other session using the database.
Creating database testdb
Error creating database testdb : ERROR: database "testdb" already exists
Connection closed!
Populating database testdb
Running insertion module...
Processing /home/hema/MailboxMiner-master/MailboxMiner2/dist/tmp/2000-July.mbox.gz.mbox
InsertModule finished successfully!
Unifying duplicate email addresses in database testdb
0
PersonalitiesModule finished successfully!
Recovering threads from database testdb
Running threads module...
ThreadsModule finished successfully!

There are no error messages displayed.But when i view the tables in pgadmin (IDE for postgresql) the records are not inserted. kindly do advice.where have i gone wrong.

note i have attached the log

[log.zip](https://github.com/nicbet/MailboxMiner/files/207784/log.zip)

**Comment by nicbet** [comment]
The first error messages indicates that "testdb" has been created previously, either manually, or by a previous run of MailboxMiner. When attempting to drop and re-created the database (command line argument --drop=true is the default unless specified otherwise, see MainCLI.java line 29) the command fails as the database appears to be currently opened and accessed by someone else, or some other application.

The output above indicates that it could not parse any records from the mbox file. According to the attached logs your are accessing a file that is compressed with gzip. Please unpack the file and try again. The repository has a sample 2000-July.mbox file in the samples directory that is uncompressed and can be used for testing.

**Comment by HEMA-MATHAVAN** [comment]
hi 
Thanks for the reply.

I closed all other applications that are using the database, my first error got cleared(thanks to u).

As you can see i am using the sample 2000-july.mbox file for testing.The following comment says that i must gzip the mbox. so i manually gzipped 2000-july.mbox.

> "Usage: $0 dir_with_gzipped_mbox_files database_url_and_port database_name user_name user_password"
> "Example: $0 mbox/ //mydb.local:5432 mm2_eclipse_list samantha ahtnamas"

Here is an output from using the uncompressed 2000-july.mox.The folder test_data contains 2000-july.mbox in uncompressed form. i am getting the following error.Still no records got inserted

```
[root@localhost hema]#  cd test_data
[root@localhost test_data]# ls
2000-July.mbox

```

`[root@localhost dist]#  sh import.sh /home/hema/test_data //localhost:5432 testdb hema password`

Unpacking mbox files to /home/hema/MailboxMiner-master/MailboxMiner2/dist/tmp
**ls: cannot access /home/hema/test_data/*.gz: No such file or directory**
Creating database testdb
[LOG] Connection to PostgreSQL 9.4.6 successful!
Dropping existing database testdb
Database testdb successfully dropped!
Creating database testdb
Database testdb successfully created!
Connection closed!
Populating database testdb
Running insertion module...
InsertModule finished successfully!
Unifying duplicate email addresses in database testdb
0
PersonalitiesModule finished successfully!
Recovering threads from database testdb
Running threads module...
ThreadsModule finished successfully!

What must i do? must i gzip the mbox file or use it as such. The command searches for files with extension .gz but according to your previous comment i am suppose to use mbox file as such(which is contradicting).kindly direct.

**Comment by HEMA-MATHAVAN** [comment]
Hi Nicolas,

I tried renaming the file from 2000-july.mbox to 2000-july.gz. Actually i didnt compress the file just renamed it. Now i can see that the mbox file could be parsed but the log still shows some error. Still the records are not inserted. i have attached the log for reference.

`[root@localhost dist]#  sh import.sh /home/hema/test_data //localhost:5432 testdb hema password`

 Unpacking mbox files to /home/hema/MailboxMiner-master/MailboxMiner2/dist/tmp
Creating database testdb
[LOG] Connection to PostgreSQL 9.4.6 successful!
Dropping existing database testdb
Database testdb successfully dropped!
Creating database testdb
Database testdb successfully created!
Connection closed!
Populating database testdb
Running insertion module...
Processing /home/hema/MailboxMiner-master/MailboxMiner2/dist/tmp/2000-July.gz.mbox
**There were errors while running the insert module!**
Unifying duplicate email addresses in database testdb
0
PersonalitiesModule finished successfully!
Recovering threads from database testdb
Running threads module...
ThreadsModule finished successfully!

The tool doesnt accept an gzipped mbox file(as stated in the comment). which literally means a compressed file. Just renaming the file did the task(parsed the mbox).

[log.zip](https://github.com/nicbet/MailboxMiner/files/210697/log.zip)

**Comment by nicbet** [comment]
I've just checked that a manual execution of the steps succeeds. Some things were broken since I've touched the code last in 2009 (Postgresql 9.1 changed the string escaping defaults) and were fixed in b56f5d42e35233e0f13b9bcdb59e1350024541f8.

Please checkout the `mvn-build` branch of the repository for the updated code.
1. Run a postgresql database using docker on port 15432
   `docker run --name some-postgres -p 15432:5432 -e POSTGRES_PASSWORD=secret -d postgres`
2. Create the template database `mm2-template-database` and execute the included `template_database.sql` file against it to create the table structure. You may need to unzip the sql file first using `gzip -d`. Ignore all `ROLE` errors.
3. Test whether you can create the mailbox database. I'm using the executable jar file produced from `mvn package` of the `mvn-build` branch of this repository.
   
   ```
   java -Xmx4000M -jar mailboxmina2-0.0.1-SNAPSHOT.jar -connection //192.168.99.100:15432/ -  username postgres -password secret -dbname test -module create -drop true
   [LOG] Connection to PostgreSQL 9.5.2 successful!
   Dropping existing database test
   Error dropping database test : ERROR: database "test" does not exist
   Creating database test
   Database test successfully created! 
   Connection closed!
   ```
4. Test whether you can parse and insert the sample box file. `ESCAPE_STRING` has changed with PostgreSQL 9.1 and above and I've update the `mvn-build` branch code to properly prefix all escaped string with `E`.
   
   ```
   java -Xmx4000M -jar ../MailboxMiner2/target/mailboxmina2-0.0.1-SNAPSHOT.jar  -connection //192.168.99.100:15432/test -username postgres -password secret -module insert -debug -logfile test-insert.log -verbosity 3 -path ./2000-July.mbox
   Running insertion module...
   Processing /Volumes/Scratch/mailboxminer2/MailboxMiner/sample/./2000-July.mbox
   InsertModule finished successfully!
   ```
   
   The insert log should read:
   
   ```
   DEBUG] InsertModule :: Processing /Volumes/Scratch/mailboxminer2/MailboxMiner/sample/./2000-July.mbox
   [DEBUG-3] MailboxParser :: Split into 441 messages!
   [DEBUG] InsertModule :: Extracted 441 messages!
   [DEBUG] InsertModule :: Encountered 882 duplicates!
   [DEBUG] InsertModule :: Inserting messages into Database...
   ```
5. Test whether the persons module can successfully detect unique personalities
   
   ```
   java -Xmx4000M -jar ../MailboxMiner2/target/mailboxmina2-0.0.1-SNAPSHOT.jar  -connection //192.168.99.100:15432/test -username postgres -password secret -module persons -debug -logfile test-persons.log -verbosity 3
   153
   PersonalitiesModule finished successfully!
   ```
6. Test whether the threads module can run successfully and recover all thread hierarchies
   
   ```
   java -Xmx4000M -jar ../MailboxMiner2/target/mailboxmina2-0.0.1-SNAPSHOT.jar  -connection //192.168.99.100:15432/test -username postgres -password secret -module threads -debug -logfile test-threads.log -verbosity 3
   Running threads module...
   ThreadsModule finished successfully!
   ```
   
   The log output should read:
   
   ```
   less test-threads.log
   [LOG] Connection to PostgreSQL 9.5.2 successful!
   [DEBUG-1] Running thread generation...
   [DEBUG-1] Dropping existing thread associations...
   [DEBUG-1] Running heuristic: in-reply...
   [LOG] The heuristic could resolve 224 parent relations!
   [LOG] Storing associations found by in-reply-to heuristic in the database...
   [DEBUG-1] Running heuristic: references...
   [LOG] The heuristic could resolve 142 parent relations!
   [LOG] Storing associations found by references heuristic in the database...
   [DEBUG-1] Running heuristic: subjects...
   [LOG] The heuristic could resolve 270 parent relations!
   [LOG] Storing associations found by in-reply-to heuristic in the database...
   [DEBUG-1] Calculating message roots...
   [DEBUG-3] 312 parent relations are known!
   [LOG] Storing 441 roots in database...
   ```

**Comment by HEMA-MATHAVAN** [comment]
Thanks....The tool works fine now.......

**Comment by nicbet** [comment]
Great!
